apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter
spec:
  selector:
    matchLabels:
      app: exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: exporter
    spec:
      containers:
      - name: exporter
        image: keitam0/demo-exporter:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
